apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-role
  namespace: redis
rules:
- apiGroups: ["apps", ""]
  resources: ["statefulsets", "statefulsets/scale", "pods"]
  verbs: ["get","update","patch","list","watch"]

