apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rolebinding
  namespace: redis
subjects:
- kind: ServiceAccount
  name: redis-sa
  namespace: redis  
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io

