apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-role
  namespace: elasticsearch
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets/scale"]
  verbs: ["get","list","create"]
