apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-elasticsearch
  namespace: elasticsearch
spec:
  timeZone: "Europe/Rome"
  schedule: "28 8 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: elasticsearch-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            # command:
            # - /bin/sh
            # - -c
            # - kubectl scale statefulsets elasticsearch-master -n elasticsearch --replicas=0
            args:
              - scale
              - statefulsets
              - elasticsearch-master   
              - --namespace=elasticsearch
              - --replicas=0
            #- kubectl patch statefulsets elasticsearch-master -p '{"spec":{"replicas":0}}'
          restartPolicy: OnFailure
          
          
          

