apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redmine
  namespace: cluster-config
spec:
  targetNamespace: redmine
  releaseName: redmine
  chart:
    spec:
      chart: redmine
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "20.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redmine-values