# Default values
# https://github.com/bitnami/charts/blob/main/bitnami/redmine/values.yaml
global:
  defaultStorageClass: "csi-hostpath-sc-retain"
  postgresql:
    auth:
      password: "P@assword"
mariadb:
  auth:
    rootPassword: "P@assword"
    password: "P@assword"
redminePassword: "P@assword"
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  accessModes:
    - ReadWriteMany

replicaCount: 2