apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
subjects:
- kind: ServiceAccount
  name: clusterrole-sa
  namespace: cluster-role
roleRef:
  kind: ClusterRole
  name: cluster-role-master
  apiGroup: rbac.authorization.k8s.io