apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-rolebinding
subjects:
- kind: ServiceAccount
  name:  Cluster-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: Cluster-role
  apiGroup: rbac.authorization.k8s.io