apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  Cluster-role
rules:
- apiGroups: ["apps", ""]
  resources: ["statefulsets", "statefulsets/scale", "pods"]
  verbs: ["get","update","patch","list","watch"]

