apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-master
rules:
- apiGroups: ["apps", "", "storage.k8s.io"]
  resources: ["statefulsets", "statefulsets/scale", "pods", "storageclasses"]
  verbs: ["get","update","patch","list","watch"]
