apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - namespace.yaml
  - kubectl-redispod/kubectl-redispod.yaml
  - Role/Role.yaml
  - Role/RoleBinding.yaml
  - Role/ServiceAccount.yaml
configMapGenerator:
  - name: redis-values
    namespace: cluster-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml