apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  labels:
    app: kubectl
  namespace: cluster-config 
spec:
  serviceAccountName: elasticsearch-sa
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - "while true; do echo 'Running kubectl...'; sleep 3600; done"
  restartPolicy: Always
 