apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-access-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-access
  template:
    metadata:
      labels:
        app: root-access
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: [ "sleep", "infinity" ]
          securityContext:
            runAsUser: 0
          stdin: true
          tty: true