apiVersion: v1
kind: Pod
metadata:
  name: root-access
  labels:
    app: root-access
spec:
  serviceAccountName: elasticsearch-sa
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: [ "sleep", "infinity" ]
  securityContext:
    runAsUser: 0
    stdin: true
    tty: true