#https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml

service:
  ## @param service.type MinIO&reg; service type
  ##
  type: NodePort

console:
  enabled: true

auth:
  rootUser: "giuseppe"
  rootPassword: "minio123"