apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-rolebinding
  namespace: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch-master
  namespace: elasticsearch  
roleRef:
  kind: Role
  name: elasticsearch-role
  apiGroup: rbac.authorization.k8s.io

